export const authconstant = {
  USERSIGNUPREQUEST: "USERSIGNUPREQUEST",
  USERSIGNUPSUCCESS: "USERSIGNUPSUCCESS",
  USERSIGNUPFAILURE: "USERSIGNUPFAILURE",

  USERLOGINREQUEST: "USERLOGINREQUEST",
  USERLOGINSUCCESS: "USERLOGINSUCCESS",
  USERLOGINFAILURE: "USERLOGINFAILURE",

  USERLOGOUTREQUEST: "USERLOGOUTREQUEST",
  USERLOGOUTSUCCESS: "USERLOGOUTSUCCESS",
  USERLOGOUTFAILURE: "USERLOGOUTFAILURE",
};

export const taskconstant = {
  ADDTASKREQUEST: "ADDTASKREQUEST",
  ADDTASKSUCCESS: "ADDTASKSUCCESS",
  ADDTASKFAILURE: "ADDTASKFAILURE",

  DELETETASKREQUEST: "DELETETASKREQUEST",
  DELETETASKSUCCESS: "DELETETASKSUCCESS",
  DELETETASKFAILURE: "DELETETASKFAILURE",

  UPDATETASKREQUEST: "UPDATETASKREQUEST",
  UPDATETASKSUCCESS: "UPDATETASKSUCCESS",
  UPDATETASKFAILURE: "UPDATETASKFAILURE",

  GETTASKREQUEST: "GETTASKREQUEST",
  GETTASKSUCCESS: "GETTASKSUCCESS",
  GETTASKFAILURE: "GETTASKFAILURE",

  GETALLTASKREQUEST: "GETALLTASKREQUEST",
  GETALLTASKSUCCESS: "GETALLTASKSUCCESS",
  GETALLTASKFAILURE: "GETALLTASKFAILURE",
};
